name: LevelUp
markdown: redcarpet
safe: false
port: 4000
baseurl: "/refresh.twlevelup.github.io"
pygments: true
destination: ./_site
plugins: ./_plugins
exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, vendor]
sass:
    style: expanded
    deploy_style: compressed
    compile_in_place: false
